[project]
name = "rocketseat-study"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.2"
dependencies = [
    "ipykernel>=7.1.0",
    "notebook>=7.5.1",
    "pandas>=2.3.3",
]
